name: pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: npm run build --if-present
  test-unit:
    runs-on: macos-10.15
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn test:unit
  test-integration:
    runs-on: macos-10.15
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn test:integration
  test-e2e:
    runs-on: macos-10.15
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn test:e2e
  build-push:
    runs-on: ubuntu-latest
    needs: [test-e2e,test-integration,test-unit]
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: arfrodiyaz
          password: Fl33t-m4n4g3m3nt
      -
        name: Set up docker build
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: arfrodiyaz/fleet-management:latest
